apiVersion: v1
kind: Service
metadata:
  name: streaming-mongo
  labels:
    app: streaming-mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None  # Headless service
  selector:
    app: streaming-mongo