#FROM ubuntu:latest
#LABEL authors="hanam"
#
#ENTRYPOINT ["top", "-b"]

#version: '3.8'
#services:
#  rabbitmq:
#    image: rabbitmq:4.0-management
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    environment:
#      RABBITMQ_DEFAULT_USER: guest
#      RABBITMQ_DEFAULT_PASS: guest
