apiVersion: v1
kind: Secret
metadata:
  name: user-postgres-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=       # base64 for "postgres"
  POSTGRES_PASSWORD: MTIzNA==  # base64 for "1234"
  POSTGRES_DB: dXNlcnMK   # base64 for "users"