server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8080
          predicates:
            - Path=/userapi/**

        - id: music-service-songs
          uri: http://music-service:8080
          predicates:
            - Path=/songs/**

        - id: music-service-playlists
          uri: http://music-service:8080
          predicates:
            - Path=/playlists/**

#        - id: socialmedia-service
#          uri: http://socialmedia-service:8080
#          predicates:
#            - Path=/socialmedia/**
        - id: streaming-service
          uri: http://streaming-service:8080
          predicates:
            - Path=/streaming/**
         
