server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/user/**

        - id: music-service-songs
          uri: http://localhost:8082
          predicates:
            - Path=/songs/**

        - id: music-service-playlists
          uri: http://localhost:8082
          predicates:
            - Path=/playlists/**

        - id: socialmedia-service
          uri: http://localhost:8083
          predicates:
            - Path=/socialmedia/**
        - id: streaming-service
          uri: http://localhost:8084
          predicates:
            - Path=/streaming/**
         
