
services:
  music-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: music-service-app
    ports:
      - "8082:8080"
    depends_on:
      - postgres
      - redis_cache
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/music
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_DATA_REDIS_HOST=redis_cache
      - SPRING_DATA_REDIS_PORT=6379
    restart: always
  postgres:
    image: postgres
    container_name: music-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=music
    restart: always
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # RabbitMQ protocol (AMQP)
      - "15672:15672"   # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  redis_cache:
    image: redis:latest
    container_name: redisCache_music
    ports:
      - "6379:6379"

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisInsight_music
    ports:
      - "5540:5540"
    restart: always
