apiVersion: apps/v1
kind: Deployment
metadata:
  name: socialmedia-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socialmedia-service
  template:
    metadata:
      labels:
        app: socialmedia-service
    spec:
      containers:
        - name: socialmedia-service
          image: faridamousa/socialmedia-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: socialmedia-mongo-secret
                  key: URI
            - name: SPRING_DATA_MONGODB_DATABASE
              value: socialmedia
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_USER
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_PASS
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"