apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming-service
  template:
    metadata:
      labels:
        app: streaming-service
    spec:
      volumes:
        - name: media-volume
          persistentVolumeClaim:
            claimName: media-pvc

      initContainers:
        - name: copy-ad-file
          image: faridamousa/streaming-service
          command:
            - cp
            - /app/static-media/f47ac10b-01cc-4372-a567-0e02b2c3d479
            - /app/media/f47ac10b-01cc-4372-a567-0e02b2c3d479
          volumeMounts:
            - name: media-volume
              mountPath: /app/media

      containers:
        - name: streaming-service
          image: habibahilal/streaming-service
          ports:
            - containerPort: 8080
          env:
            - name: user-service
              value: http://user-service:8080
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: streaming-mongo-secret
                  key: URI
            - name: SPRING_DATA_MONGODB_DATABASE
              value: 3ateya_and_Co
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_USER
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_DEFAULT_PASS
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
          volumeMounts:
            - name: media-volume
              mountPath: /app/media
