services:
  postgres:
    image: postgres
    container_name: postgres_userApp
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  redis_cache:
    image: redis:latest
    container_name: redisCache_userApp
    ports:
      - "6379:6379"

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisInsight_userApp
    ports:
      - "5540:5540"
    restart: always

  app:
    build: .
    container_name: userApp
    depends_on:
      - postgres
      - redis_cache
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/users
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATA_REDIS_HOST: redis_cache
      SPRING_DATA_REDIS_PORT: 6379


