apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: socialmedia-mongo
spec:
  serviceName: "socialmedia-mongo"  # Must match headless service
  replicas: 1  #FIXME CHANGE
  selector:
    matchLabels:
      app: socialmedia-mongo
  template:
    metadata:
      labels:
        app: socialmedia-mongo
    spec:
      containers:
        - name: socialmedia-mongo
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: socialmedia-mongo-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: socialmedia-mongo-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
          volumeMounts:
            - name: socialmedia-mongo-persistent-volume
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: socialmedia-mongo-persistent-volume
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi       #FIXME CHANGE